name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest]
        php: [8.2]
        stability: [prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: macOS installation
        if: runner.os == 'macOS'
        run: |
          brew install flac vorbis-tools
          brew install act fribidi libarchive libsamplerate lz4 p11-kit sqlite antigen gd libass libsndfile lzo p7zip srt aom gdk-pixbuf libassuan libsodium m4 pandoc svt-av1 apr geckodriver libavif libsoxr mailpit pango tesseract apr-util gettext libb2 libssh mbedtls pcre theora argon2 ghostscript libbluray libssh2 meilisearch pcre2 tidy-html5 aribb24 giflib libde265 libtasn1 mpdecimal php unar aspell glib libevent libtiff mpg123 php@8.0 unbound autoconf gmp libgcrypt libtool php@8.1 unixodbc automake gnupg libgit2 libunibreak pinentry brotli gnutls libgit2@1.6 libunistring pixman wavpack ca-certificates go libgpg-error libusb pkg-config webp cairo gpgme libheif libvidstab nettle poppler x264 cjson graphite2 libidn libvmaf nginx python-certifi x265 curl harfbuzz libidn2 libvorbis nmap python-mutagen xorgproto dav1d highway libksba libvpx npth python@3.11 xvid djvulibre icu4c liblinear libx11 nspr rav1e xz dnsmasq imagemagick liblqr libxau nss readline exa imath libmobi libxcb oniguruma redis exiftool jasper libnghttp2 libxdmcp opencore-amr rtmpdump z3 exiv2 jbig2dec libogg libxext openexr rubberband zeromq ffmpeg jpeg-turbo libomp libxrender openjdk zimg jpeg-xl libpng libzip openjpeg sdl2 zstd fontconfig krb5 libpq little-cms2 openldap shared-mime-info freetds lame libraw llvm openssl@1.1 six freetype leptonica librist llvm@16 openssl@3 snappy frei0r libao librsvg lua opus speex

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest
